version: "2"

services:
  postgres:
    image: postgres:10.7-alpine
    restart: always
    environment:
      - POSTGRES_DB=simios
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - simios:/var/lib/postgresql

volumes:
  simios: {}
