service: simios

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  environment:
    NODE_ENV: dev

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  include:
    - environments/.env.dev

resources:
  Resources:
    LambdaSecurityGroup:
      Properties:
        GroupDescription: Lambda security group
        GroupName: 'lambda-sg'
        VpcId: 'vpc-f091eb8a'
      Type: AWS::EC2::SecurityGroup

functions:
  isSimian:
    handler: app/handler.isSimian
    events:
      - http:
          path: simian
          method: post
          cors: true
  stats:
    handler: app/handler.stats
    events:
      - http:
          path: stats
          method: get
          cors: true
    vpc:
      securityGroupIds:
        - {Ref: LambdaSecurityGroup}
      subnetIds:
        - "subnet-53416b0f"
        - "subnet-0edcf269"
        - "subnet-92af56df"
